// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17GuWt65VOeHGKXaGAylfygqKQ5Jho7I',
    appId: '1:512012526908:web:77a1383f704d0013426a39',
    messagingSenderId: '512012526908',
    projectId: 'appliedplus-a9697',
    authDomain: 'appliedplus-a9697.firebaseapp.com',
    storageBucket: 'appliedplus-a9697.firebasestorage.app',
    measurementId: 'G-KFBVVYY91R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL8WAeffBvA7SYOeAhwD7RnknuD58IBFc',
    appId: '1:512012526908:android:c8a61a35e3dfbb9d426a39',
    messagingSenderId: '512012526908',
    projectId: 'appliedplus-a9697',
    storageBucket: 'appliedplus-a9697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJeAtIU_ZXwgao0DuoKf3pCdKV7xl2mnI',
    appId: '1:512012526908:ios:84f85f9409d464e7426a39',
    messagingSenderId: '512012526908',
    projectId: 'appliedplus-a9697',
    storageBucket: 'appliedplus-a9697.firebasestorage.app',
    iosBundleId: 'com.example.appliedjobs',
  );

}